[language-server]
emmet-lsp = {  command = "emmet-language-server",  args = ["--stdio"] }

[[language]]
name = "html"
language-servers = [ "emmet-lsp", "vscode-html-language-server" ]

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "jsx"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "tsx"
auto-format = true

[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "config"
scope = "source.conf"
file-types = [ "conf" ]
comment-token = "#"
roots = []
indent = { tab-width = 4, unit = "    " }
